export const environment = {
  "pallet_town": [
	[
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'grass' },
	  { canWalk: true, type: 'grass' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'grass' },
	  { canWalk: true, type: 'grass' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'housewall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'pane' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'door', warp:{name: "red_house", x:3, y:7}},
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'pane' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'door', warp:{name: "blue_house", x:3, y:7}},
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'pane' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'door', warp:{name: "laboratory", x:5, y:11}},
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: false, type: 'house' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'panewall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'wall' },
	],
	[
	  { canWalk: false, type: 'waall' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: false, type: 'water' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: true, type: 'floor' },
	  { canWalk: false, type: 'waall' },
	],
	[
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	  { canWalk: false, type: 'wall' },
	],
  ],
  "red_house": [
	[
	  {canWalk: false, type: 'bookshelf'},
	  {canWalk: false, type: 'bookshelf'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'window'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'window'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'window'}
	],
	[
	  {canWalk: false, type: 'bookshelf'},
	  {canWalk: false, type: 'bookshelf'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: false, type: 'television'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'stairs', warp:{name: "red_bedroom", x:7, y:1}}
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'footstole'},
	  {canWalk: false, type: 'table'},
	  {canWalk: false, type: 'table'},
	  {canWalk: true, type: 'footstole'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'}
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'footstole'},
	  {canWalk: false, type: 'table'},
	  {canWalk: false, type: 'table'},
	  {canWalk: true, type: 'footstole'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'}
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:5, y:6}},
	  {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:5, y:6}},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
  ],
  "red_bedroom": [
	[
	  {canWalk: false, type: 'computer'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'window'},
	  {canWalk: false, type: 'wall'},
	  {canWalk: false, type: 'window'}
	],
	[
	  {canWalk: false, type: 'computer'},
	  {canWalk: false, type: 'table'},
	  {canWalk: false, type: 'table'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'stairs', warp:{name: "red_house", x:7, y:1}}
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: false, type: 'television'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'}
	],
	[
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: false, type: 'nintendo'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'}
	],
	[
	  {canWalk: true, type: 'bed'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: false, type: 'plant'},
	  {canWalk: true, type: 'floor'},
	],
	[
	  {canWalk: true, type: 'bed'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: true, type: 'floor'},
	  {canWalk: false, type: 'plant'},
	  {canWalk: true, type: 'floor'},
	],
  ],
  "blue_house": [
        [
            {canWalk: false, type: 'bookshelf'},
            {canWalk: false, type: 'bookshelf'},
            {canWalk: false, type: 'wall'},
            {canWalk: false, type: 'picture'},
            {canWalk: false, type: 'wall'},
            {canWalk: false, type: 'window'},
            {canWalk: false, type: 'bookshelf'},
            {canWalk: false, type: 'bookshelf'}
        ],
        [
            {canWalk: false, type: 'bookshelf'},
            {canWalk: false, type: 'bookshelf'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: false, type: 'bookshelf'},
            {canWalk: false, type: 'bookshelf'}
        ],
        [
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
        ],
        [
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'footstole'},
            {canWalk: false, type: 'table'},
            {canWalk: false, type: 'table'},
            {canWalk: true, type: 'footstole'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
        ],
        [
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'footstole'},
            {canWalk: false, type: 'table'},
            {canWalk: false, type: 'table'},
            {canWalk: true, type: 'footstole'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'}
        ],
        [
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'}
        ],
        [
            {canWalk: false, type: 'plant'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: false, type: 'plant'},
        ],
        [
            {canWalk: false, type: 'plant'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:13, y:6}},
            {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:13, y:6}},
            {canWalk: true, type: 'floor'},
            {canWalk: true, type: 'floor'},
            {canWalk: false, type: 'plant'},
        ],
    ],
  "laboratory":[
      [
          {canWalk: false, type: 'wall'},
          {canWalk: false, type: 'wall'},
          {canWalk: false, type: 'wall'},
          {canWalk: false, type: 'wall'},
          {canWalk: false, type: 'reward'},
          {canWalk: false, type: 'reward'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
      ],
      [
          {canWalk: false, type: 'desk'},
          {canWalk: false, type: 'desk'},
          {canWalk: false, type: 'table'},
          {canWalk: false, type: 'table'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: false, type: 'table'},
          {canWalk: false, type: 'table'},
          {canWalk: false, type: 'table'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
      ],
      [
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
          {canWalk: false, type: 'bookshelf'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
      [
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:12, y:12}},
          {canWalk: true, type: 'carpet', warp:{name: "pallet_town", x:12, y:12}},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
          {canWalk: true, type: 'floor'},
      ],
  ]
};