export const environment = {
  "pallet_town": [
    [
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'grass' },
      { canWalk: true, type: 'grass' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'grass' },
      { canWalk: true, type: 'grass' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'housewall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'pane' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'door', name: "red_house"},
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'pane' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'door', name:'blue_house'},
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'pane' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'door', name: "chen_house"},
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: false, type: 'house' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'panewall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'wall' },
    ],
    [
      { canWalk: false, type: 'waall' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: false, type: 'water' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: true, type: 'floor' },
      { canWalk: false, type: 'waall' },
    ],
    [
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
      { canWalk: false, type: 'wall' },
    ],
  ],
  "red_house": [
    [
      {canWalk: false, type: 'bookshelf'},
      {canWalk: false, type: 'bookshelf'},
      {canWalk: false, type: 'wall'},
      {canWalk: false, type: 'window'},
      {canWalk: false, type: 'wall'},
      {canWalk: false, type: 'window'},
      {canWalk: false, type: 'wall'},
      {canWalk: false, type: 'window'}
    ],
    [
      {canWalk: false, type: 'bookshelf'},
      {canWalk: false, type: 'bookshelf'},
      {canWalk: true, type: 'floor'},
      {canWalk: false, type: 'television'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'stairs'}
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'footstole'},
      {canWalk: false, type: 'table'},
      {canWalk: false, type: 'table'},
      {canWalk: true, type: 'footstole'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'}
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'footstole'},
      {canWalk: false, type: 'table'},
      {canWalk: false, type: 'table'},
      {canWalk: true, type: 'footstole'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'}
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
    ],
    [
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'carpet', name:"pallet_town"},
      {canWalk: true, type: 'carpet', name:"pallet_town"},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
      {canWalk: true, type: 'floor'},
    ],
  ]
};